"""Static reference content for the Tactical Playbook tab.

Phases, the suggested tag vocabularies (used as one-tap chips in the editor),
and the built-in Library of general table-tennis tactics. None of this is stored
in the database — the Library is browse-only reference content that the user can
copy up into *My Tactics*.

Content style: Vietnamese sentences mixing standard English table-tennis jargon
(serve, return, push, flick, loop, block, forehand/FH, backhand/BH, third ball…).
Keys stay English/stable so copied tactics keep their source link.
"""
from __future__ import annotations

# (key, label) in display order. Drives both the phase selector and grouping.
PHASES: list[tuple[str, str]] = [
    ("serve", "Serve"),
    ("receive", "Return"),
    ("third_ball", "Third ball"),
    ("rally", "Rally"),
    ("general", "Chung"),
]

# Suggested chips for the editor (free text — users can type their own too).
SPIN_TAGS = ["Backspin", "Topspin", "Sidespin", "No-spin"]
PLACEMENT_TAGS = ["Short", "Half-long", "Long", "FH", "Middle", "BH"]
OPPONENT_STYLES = ["Attacker", "Blocker", "Chopper", "Looper", "Penhold", "All-round"]


def _t(
    key: str,
    phase: str,
    title: str,
    when_to_use: str,
    how_to: str,
    follow_up: str,
    risk: str,
    opponent_styles: list[str],
    tags: list[str],
    source: str | None = None,
    source_url: str | None = None,
) -> dict:
    return {
        "key": key,
        "phase": phase,
        "title": title,
        "when_to_use": when_to_use,
        "how_to": how_to,
        "follow_up": follow_up,
        "risk": risk,
        "opponent_styles": opponent_styles,
        "tags": tags,
        "source": source,  # name of the coaching source (None = hand-authored)
        "source_url": source_url,
    }


# Curated general tactics.
LIBRARY_TACTICS: list[dict] = [
    # ----------------------------------------------------------------- serve
    _t(
        "serve_short_backspin_bh", "serve",
        "Short backspin serve vào BH",
        "Đối thủ push trái yếu, hay return bằng push lại bàn",
        "Serve 2 nảy, backspin nặng, rơi short vào ô BH",
        "Sẵn sàng loop moi hoặc đánh third ball nếu họ push dài",
        "Bị banana flick nếu bóng nảy cao hoặc đi dài",
        ["Blocker", "Chopper"], ["Backspin", "Short", "BH"],
    ),
    _t(
        "serve_fast_long_elbow", "serve",
        "Fast long serve vào khuỷu tay",
        "Đối thủ đứng sát bàn, chờ serve ngắn",
        "Serve dài thật nhanh, topspin/sidespin, nhắm điểm khuỷu tay (crossover)",
        "Bám theo block/counter quả return lả lướt",
        "Nếu đoán được, đối thủ loop/smash return rất mạnh",
        ["Blocker", "Penhold"], ["Topspin", "Long", "Middle"],
    ),
    _t(
        "serve_pendulum_side_short_mid", "serve",
        "Pendulum serve short vào middle",
        "Muốn hạn chế góc return của đối thủ",
        "Pendulum serve sidespin, short, rơi vào giữa bàn để bó góc",
        "Đoán hướng return theo sidespin rồi vào third ball",
        "Sidespin ít hiệu quả với người đọc xoáy tốt",
        ["Attacker", "All-round"], ["Sidespin", "Short", "Middle"],
    ),
    _t(
        "serve_tomahawk_wide_fh", "serve",
        "Tomahawk serve vào FH rộng",
        "Kéo đối thủ ra góc forehand để mở bàn",
        "Tomahawk serve (sidespin ngược), đẩy đối thủ ra mép FH",
        "Đánh vào ô trống BH sau khi họ return",
        "Mở góc cho đối thủ counter chéo",
        ["Blocker"], ["Sidespin", "Half-long", "FH"],
    ),
    _t(
        "serve_no_spin_short_fh", "serve",
        "No-spin serve short vào FH",
        "Dụ đối thủ flick/push hụt vì tưởng có xoáy",
        "Serve short, no-spin, động tác giả như backspin",
        "Block/counter quả flick lỗi của họ",
        "Đối thủ đọc được sẽ flick ăn điểm trực tiếp",
        ["Attacker", "All-round"], ["No-spin", "Short", "FH"],
    ),
    _t(
        "serve_reverse_pendulum", "serve",
        "Reverse pendulum serve",
        "Muốn quả return bật về phía FH/giữa để mình attack",
        "Lắc cổ tay ngược (phải→trái) tạo sidespin ngược; rất lừa vì giống pendulum thường",
        "Đón quả return lệch sang phải rồi loop/attack",
        "Kỹ thuật khó, dễ bị bắt bài nếu động tác chậm hoặc lộ",
        ["Attacker", "All-round"], ["Sidespin"],
        "PingSunday", "https://pingsunday.com/reverse-pendulum-serve/",
    ),
    _t(
        "serve_long_fast_deep", "serve",
        "Fast long serve sâu hết bàn",
        "Bất ngờ sau loạt serve ngắn; đối thủ đứng sát bàn",
        "Serve thật sâu (sát mép cuối bàn) và nhanh, dùng topspin hoặc sidespin",
        "Block/counter quả return vội của đối thủ",
        "Nếu đoán được, đối thủ loop/smash return rất mạnh",
        ["Blocker"], ["Topspin", "Long"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
    _t(
        "serve_vary_sidespin_same_action", "serve",
        "Đổi sidespin cùng một động tác (same action)",
        "Xuyên suốt trận để ăn điểm rẻ khi đối thủ mất tập trung",
        "Cùng một động tác tay, xen kẽ sidespin+topspin và sidespin+backspin để đối thủ đọc nhầm",
        "Attack ngay quả return lỗi (rúc lưới hoặc bay ra)",
        "Người đọc xoáy tốt sẽ không mắc bẫy",
        ["All-round"], ["Sidespin"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
    # --------------------------------------------------------------- receive
    _t(
        "receive_short_push_drop", "receive",
        "Return short / push drop sát lưới",
        "Đối thủ serve short backspin",
        "Đưa vợt vào sớm, push trả thật short (drop) sát lưới",
        "Sẵn sàng loop/đẩy nếu họ return dài",
        "Push cao sẽ bị loop/flick dứt điểm",
        ["Attacker", "Looper"], ["Backspin", "Short"],
    ),
    _t(
        "receive_banana_flick_bh", "receive",
        "Banana flick (chuối) vào BH",
        "Serve short không quá xoáy, muốn giành chủ động",
        "Dùng cổ tay banana flick (topspin/sidespin) sang góc BH đối thủ",
        "Vào nhịp đôi công ngay sau flick",
        "Hỏng nếu bóng backspin nặng hoặc quá short",
        ["Blocker", "Penhold"], ["Topspin", "Short", "BH"],
    ),
    _t(
        "receive_long_push_to_bh", "receive",
        "Push dài (long push) ghìm góc BH",
        "Chưa muốn mạo hiểm loop, cần kéo dài pha bóng",
        "Push dài, nhanh và sâu vào góc BH để hạn chế họ loop mạnh",
        "Block chờ cơ hội counter",
        "Push lỏng/nổi sẽ bị loop trước",
        ["Attacker", "Looper"], ["Backspin", "Long", "BH"],
    ),
    _t(
        "receive_attack_long_serve", "receive",
        "Loop/smash ngay quả long serve",
        "Đối thủ serve dài (lỡ hoặc cố ý)",
        "Lùi chân, loop hoặc smash ngay quả long serve để chiếm thế",
        "Tiếp tục đôi công/loop loạt 2",
        "Đọc sai spin của serve sẽ loop hụt hoặc ra ngoài",
        ["Blocker", "Chopper"], ["Topspin", "Long"],
    ),
    _t(
        "receive_return_wide_angles", "receive",
        "Return vào 2 góc rộng (wide angles)",
        "Muốn phá thế chuẩn bị third ball của đối thủ",
        "Return (push/flick) đổi hướng liên tục vào 2 mép bàn",
        "Quan sát footwork đối thủ để đoán quả kế",
        "Trả ra mép dễ lỗi nếu kiểm soát kém",
        ["All-round", "Penhold"], ["FH", "BH"],
    ),
    _t(
        "receive_return_short_stop_attack", "receive",
        "Return short để chặn attack",
        "Đối thủ chực loop quả return dài của mình",
        "Return thật short để bóng nảy ít nhất 2 lần bên kia, triệt cơ hội loop",
        "Sẵn sàng attack khi đối thủ buộc phải push/đẩy lại",
        "Return nổi cao sẽ bị flick dứt điểm",
        ["Attacker", "Looper"], ["Short"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/video/return-short-and-stop-the-attacks/",
    ),
    _t(
        "receive_neutralize_sidespin_slice", "receive",
        "Slice trị sidespin khi return reverse serve",
        "Return reverse pendulum serve hoặc serve nhiều sidespin",
        "Chủ động slice (cắt nhẹ xuống) lúc chạm bóng, nghiêng mặt vợt theo hướng xoáy để trung hoà",
        "Return vào vị trí an toàn rồi vào thế",
        "Đọc sai hướng sidespin → return ra biên",
        ["Attacker"], ["Sidespin"],
        "PingSunday", "https://pingsunday.com/how-to-return-the-reverse-pendulum-serve-in-table-tennis-coach-fang-bo/",
    ),
    _t(
        "receive_no_spin_drive", "receive",
        "Drive/đẩy chủ động quả no-spin serve",
        "Nhận ra đối thủ serve no-spin (động tác giả)",
        "Drive hoặc đẩy chủ động thay vì push — vì push quả no-spin sẽ nổi cao",
        "Vào nhịp đôi công/attack",
        "Nếu thực ra có backspin thì sẽ rúc lưới",
        ["All-round"], ["No-spin"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/question/returning-no-spin-serves/",
    ),
    _t(
        "receive_strawberry_flick", "receive",
        "Strawberry flick (flick nghịch)",
        "Mọi kiểu return khác đã bị đối thủ bắt bài, cần gây bất ngờ",
        "Flick với sidespin ngược chiều banana flick, đổi hướng bóng khó đoán",
        "Vào nhịp attack sau cú flick",
        "Kỹ thuật khó, tỉ lệ lỗi cao nếu chưa thuần thục",
        ["Blocker", "Penhold"], ["Sidespin", "Short"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/add-variety-service-returns/",
    ),
    # ------------------------------------------------------------ third_ball
    _t(
        "third_serve_short_then_loop", "third_ball",
        "Serve short → đối thủ push → loop moi",
        "Sau khi serve short backspin và đối thủ push dài lại",
        "Chủ động chờ, bước vào loop moi quả push để mở bàn",
        "Chuyển sang loop xung/đôi công loạt sau",
        "Push short bất ngờ làm hụt nhịp loop",
        ["Blocker", "Chopper"], ["Backspin", "Loop"],
    ),
    _t(
        "third_serve_attack_elbow", "third_ball",
        "Serve xong attack vào elbow",
        "Quả return của đối thủ hơi cao hoặc dài",
        "Smash/loop ngay vào điểm khuỷu tay để họ khó chọn FH hay BH",
        "Bám bàn đôi công",
        "Nếu quả return thấp/short thì không vào được",
        ["Attacker", "All-round"], ["Middle", "Loop"],
    ),
    _t(
        "third_step_around_bh_loop", "third_ball",
        "Step-around FH loop từ góc BH",
        "Quả return rơi vào góc BH, đủ dài để né người",
        "Step-around, dùng FH loop xung chéo hoặc down the line",
        "Lùi nhẹ chuẩn bị quả counter",
        "Mở toang ô FH nếu đối thủ đổi hướng",
        ["Blocker", "Penhold"], ["BH", "FH", "Loop"],
    ),
    _t(
        "third_punish_high_ball", "third_ball",
        "Smash dứt điểm quả nổi cao",
        "Đối thủ return nổi cao (push hỏng hoặc flick lỗi)",
        "Smash mạnh, dứt khoát vào ô trống",
        "Kết thúc điểm",
        "Vội/căng cứng dễ smash hỏng",
        ["Blocker", "Chopper"], ["Smash"],
    ),
    _t(
        "third_imagine_pattern", "third_ball",
        "Hình dung pattern trước khi serve",
        "Mỗi lần tới lượt mình serve",
        "Trước khi serve, tưởng tượng pattern: serve gì → đối thủ return ra sao → mình đánh third ball vào đâu; lặp lại bài nào hiệu quả (cách tập của TQ)",
        "Thực hiện đúng bài, hoàn thiện dần qua lặp lại",
        "Cứng nhắc khi đối thủ return khác dự đoán — phải có plan B",
        ["Attacker", "All-round"], ["Mindset"],
        "PingSunday", "https://pingsunday.com/third-ball-attack-table-tennis/",
    ),
    _t(
        "third_serve_short_bh_flick_wide_fh", "third_ball",
        "Serve short backspin BH → FH flick wide",
        "Bài third ball bài bản khi đối thủ hay push short về FH",
        "Serve short backspin vào BH; đối thủ push short về FH; mình FH flick sang góc FH rộng đối thủ",
        "Bám bàn đôi công sau cú flick mở bàn",
        "Quả push quá short/thấp làm hụt nhịp flick",
        ["Blocker"], ["Backspin", "FH", "Loop"],
        "PingSunday", "https://pingsunday.com/third-ball-attack-table-tennis/",
    ),
    _t(
        "third_pivot_forehand", "third_ball",
        "Pivot FH loop (né trái giật phải)",
        "Muốn dùng cú FH mạnh nhất để mở bàn",
        "Đứng pivot (lệch trái), né người dùng FH loop — tầm nhìn rộng, dễ điều hướng attack",
        "Tiếp loạt loop/đôi công",
        "Mở toang ô FH nếu đối thủ đổi hướng nhanh",
        ["Blocker", "All-round"], ["FH", "Loop"],
        "PingSunday", "https://pingsunday.com/strategy-win-table-tennis-serve-attack/",
    ),
    # --------------------------------------------------------------- rally
    _t(
        "rally_pin_bh_switch_fh", "rally",
        "Ghìm BH rồi switch sang FH rộng",
        "Đang đôi công bên BH ổn định",
        "Ép nhiều quả vào BH rồi đột ngột switch sang FH rộng",
        "Attack ô trống khi đối thủ lệch người",
        "Đổi hướng non sẽ thành quả dễ cho đối thủ",
        ["Attacker", "All-round"], ["BH", "FH"],
    ),
    _t(
        "rally_block_redirect", "rally",
        "Block đổi hướng (redirect)",
        "Đối thủ loop mạnh, mình đang bị động",
        "Block sớm và đổi hướng (ép góc ngược), giữ vợt thấp, chạm bóng sớm khi đang lên",
        "Lấy lại thế chủ động khi họ mất đà",
        "Block trễ/ngửa mặt vợt sẽ bị loop xuyên",
        ["Looper", "Attacker"], ["Block"],
    ),
    _t(
        "rally_counter_loop", "rally",
        "Counter-loop (đối giật)",
        "Cả hai cùng loop xa bàn",
        "Counter-loop sớm theo nhịp lên của bóng, mượn lực",
        "Tăng dần điểm rơi và tốc độ ép đối thủ",
        "Sai nhịp/điểm chạm sẽ loop hỏng",
        ["Looper", "Attacker"], ["Topspin", "Loop"],
    ),
    _t(
        "rally_change_pace_spin", "rally",
        "Đổi pace & spin phá nhịp",
        "Đối thủ đang vào nhịp đều",
        "Xen kẽ quả nhanh/chậm, nhiều/ít spin để phá nhịp (change of pace)",
        "Chớp quả lỡ nhịp để attack",
        "Quả chậm/nổi dễ bị attack nếu lộ ý",
        ["All-round", "Attacker"], ["Change pace"],
    ),
    _t(
        "rally_four_spots", "rally",
        "Điều bóng vào 4 spots hiểm",
        "Chủ động điều đối thủ chạy, tìm sơ hở",
        "Nhắm 4 spots: wide BH (ngoài góc), sâu góc BH, middle (khuỷu tay), và wide FH",
        "Attack ô trống khi đối thủ lệch người",
        "Đánh ra mép dễ lỗi nếu kiểm soát kém",
        ["All-round", "Attacker"], ["FH", "BH", "Middle"],
        "Samson Dubina", "https://www.samsondubina.com/tactics/various-game-styles",
    ),
    _t(
        "rally_attack_down_the_line", "rally",
        "Attack down the line (dọc biên)",
        "Đối thủ quen block/defend đường chéo (cross-court)",
        "FH loop/smash down the line vào góc BH đối thủ — hướng họ ít chờ đợi",
        "Dứt điểm hoặc ép tiếp khi họ return vội",
        "Down the line rủi ro hơn cross-court (qua phần lưới cao hơn, đường ngắn hơn)",
        ["Attacker"], ["FH", "BH"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
    _t(
        "rally_backhand_counterloop", "rally",
        "Backhand counter-loop",
        "Đối thủ loop topspin vào góc BH của mình",
        "BH counter-loop sớm — phiên bản bùng nổ hơn của BH drive, mượn spin của đối thủ",
        "Tăng dần lực và điểm rơi ép đối thủ lùi",
        "Sai nhịp hoặc điểm chạm sẽ loop hỏng",
        ["Looper", "Attacker"], ["Topspin", "BH", "Loop"],
        "Killerspin", "https://www.killerspin.com/blogs/tips/how-to-backhand-counter-loop",
    ),
    _t(
        "rally_loop_heavy_topspin_vs_blocker", "rally",
        "Loop nặng topspin ép blocker",
        "Đối thủ block kém xử lý bóng nhiều spin",
        "Nạp thật nhiều topspin vào cú loop (ưu tiên spin hơn speed) để bóng nảy vọt khi họ block",
        "Ép liên tục cho tới khi họ block lỗi/nổi cao rồi dứt điểm",
        "Người counter tốt có thể mượn spin smash lại",
        ["Blocker"], ["Topspin", "Loop"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
    # --------------------------------------------------------------- general
    _t(
        "general_play_elbow", "general",
        "Đánh elbow (crossover point)",
        "Khi không rõ nên đánh FH hay BH của đối thủ",
        "Nhắm điểm chuyển giao FH/BH (elbow / crossover) để đối thủ lưỡng lự",
        "Đánh tiếp vào ô trống do họ lệch người",
        "Đối thủ footwork tốt sẽ xử lý gọn",
        ["All-round"], ["Middle"],
    ),
    _t(
        "general_serve_by_score", "general",
        "Chọn serve theo tỉ số",
        "Các điểm quan trọng (deuce, set-point)",
        "Dùng serve an toàn/sở trường ở điểm then chốt, để dành quả tủ",
        "Triển khai bài third ball đã tập",
        "Lạm dụng một kiểu serve sẽ bị bắt bài",
        [], ["Mental"],
    ),
    _t(
        "general_target_weak_wing", "general",
        "Tập trung đánh bên yếu (weaker wing)",
        "Đã nhận ra FH hay BH đối thủ yếu hơn",
        "Liên tục ép vào cánh yếu, chỉ đổi hướng để giữ bất ngờ",
        "Dứt điểm khi họ return lỏng",
        "Đánh một bên quá lộ, đối thủ chuẩn bị trước",
        ["All-round", "Attacker"], ["FH", "BH"],
    ),
    _t(
        "general_third_ball_mindset", "general",
        "Tư duy chủ động third ball",
        "Mỗi lượt mình serve",
        "Serve với ý đồ sẵn cho third ball, không serve vô thưởng vô phạt",
        "Thực hiện đúng bài đã định",
        "Cứng nhắc theo bài khi đối thủ return khác dự đoán",
        [], ["Mindset"],
    ),
    _t(
        "general_serve_into_middle", "general",
        "Serve vào middle ép return vụng",
        "Muốn nhiều quả return yếu, ăn điểm rẻ",
        "Serve vào giữa bàn (elbow) buộc đối thủ lưỡng lự chọn FH hay BH",
        "Attack quả return vụng/yếu",
        "Đối thủ footwork và quyết định nhanh sẽ hoá giải",
        ["All-round"], ["Middle"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/video/super-effective-service-tactic/",
    ),
    _t(
        "general_consistency_70", "general",
        "Đánh 70% sức, ép đối thủ sai trước",
        "Cần chắc chắn; đối thủ kém ổn định trong rally",
        "Đánh nhiều quả ở khoảng 70% lực, thử độ bền và độ ổn định (consistency) của đối thủ",
        "Tăng lực dứt điểm khi có quả ngon",
        "Quả an toàn dễ bị attack nếu gặp người mạnh hơn",
        ["All-round"], ["Mental"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
    _t(
        "general_play_to_strength_vs_stronger", "general",
        "Đưa strength vào trận khi gặp đối thủ mạnh hơn",
        "Đấu với người mạnh hơn rõ rệt",
        "Bằng mọi giá đưa điểm mạnh nhất của mình vào trận, nhắm vào vùng yếu của họ; dám chơi ngoài comfort zone",
        "Khai thác liên tục nếu strength phát huy",
        "Mạo hiểm cao — có thể hỏng nhiều nếu không vào nhịp",
        ["Attacker", "All-round"], ["Mental"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/tactics-beat-much-stronger-player/",
    ),
    _t(
        "general_toolbox_tactics", "general",
        "Chuẩn bị sẵn 'toolbox' nhiều tactics",
        "Mỗi đối thủ một kiểu — không có tactic nào thắng tất cả",
        "Chuẩn bị nhiều tactics khác nhau; thử và giữ cái nào gây khó cho đối thủ này, bỏ cái không hiệu quả",
        "Tập trung khai thác tactic đang ăn",
        "Đổi bài liên tục mà không khai thác đủ cũng kém hiệu quả",
        [], ["Mindset", "Mental"],
        "Tom Lodziak", "https://www.tabletenniscoach.me.uk/top-10-tactics-to-win-points-in-local-league-table-tennis/",
    ),
]
